update year
dallasnews/dmn-vendor-wrapper pull request #61
Opened 2024-12-30 20:11 UTC by mujbadar

2024-12-30 20:11 UTC, mujbadar commented on src/footer/footer.html
> +              <a href="https://www.dallasnews.com/news/obituaries/"
prettier

2024-12-30 20:22 UTC, cks approved these changes

2024-12-30 20:47 UTC, rlsmileg requested changes
Changes look good. Please add test steps. Can't you just build and then look at html in browser?

2024-12-30 20:47 UTC, suwaphitb approved these changes
~~Code LGTM~~
Please address Rechard's feedback.

2025-01-02 16:02 UTC, mujbadar commented
@rlsmileg @suwaphitb Built and repushed. Here is the local output.
<img width="1784" alt="Screenshot 2025-01-02 at 9 59 40 AM" src="https://github.com/user-attachments/assets/d8aae52e-e4f3-4973-865f-edc02025efb7" />

2025-01-03 15:10 UTC, suwaphitb commented
Thank you so much. 
The changes look good, and the results match our expectations. 👍🏼 
2️⃣ 0️⃣ 2️⃣ 5️⃣  🎉 🎉 🎉 🎉

2025-01-06 19:20 UTC, HaydenManning approved these changes

2025-01-07 17:02 UTC, merged